export const sentences = [
  "The quick brown fox jumps over the lazy dog.",
  "To be or not to be, that is the question.",
  "All that glitters is not gold.",
  "A journey of a thousand miles begins with a single step.",
  "Practice makes perfect.",
  "The early bird catches the worm.",
  "Actions speak louder than words.",
  "Where there's a will, there's a way.",
  "Rome wasn't built in a day.",
  "The pen is mightier than the sword.",
  "A picture is worth a thousand words.",
  "Time flies when you're having fun.",
  "The best things in life are free.",
  "Every cloud has a silver lining.",
  "Life is what happens while you're busy making other plans.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
];
